spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/1804A

  rabbitmq:
    password: guest
    username: guest
    host: 127.0.0.1
    port: 5672
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/chuchu?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      redis:
        host: 127.0.0.1
        port: 6379
        jedis:
          pool:
            max-idle: 8
            min-idle: 0

server:
  port: 8887